/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/CastleA.glb -o src/Model.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/CastleA.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.HeartVid.geometry} material={nodes.HeartVid.material} />
      <mesh geometry={nodes.water.geometry} material={nodes.water.material} />
      <mesh geometry={nodes.gods.geometry} material={nodes.gods.material} />
      <mesh geometry={nodes.LogoCupid.geometry} material={nodes.LogoCupid.material} position={[0.001, 4.18, -0.006]} />
      <mesh geometry={nodes.bow.geometry} material={nodes.bow.material} position={[-0.011, 1.262, -2.117]} />
      <mesh geometry={nodes.MirrorFrame.geometry} material={nodes.MirrorFrame.material} />
      <mesh geometry={nodes.wings.geometry} material={nodes.wings.material} />
      <mesh geometry={nodes.hoofGlass.geometry} material={nodes.hoofGlass.material} />
      <mesh geometry={nodes.scroll.geometry} material={nodes.scroll.material} />
      <mesh geometry={nodes.Hallos.geometry} material={nodes.Hallos.material} />
      <mesh geometry={nodes.floor.geometry} material={nodes.floor.material} />
      <mesh geometry={nodes.castle.geometry} material={nodes.castle.material} />
      <mesh geometry={nodes.castleHeart.geometry} material={nodes.castleHeart.material} />
      <mesh geometry={nodes.floorHeart.geometry} material={nodes.floorHeart.material} />
      <mesh geometry={nodes.castleLights.geometry} material={nodes.castleLights.material} />
      <mesh geometry={nodes.castleHeartMask.geometry} material={nodes.castleHeartMask.material} />
      <mesh geometry={nodes.decor.geometry} material={nodes.decor.material} />
      <mesh geometry={nodes.castleGodsWalls.geometry} material={nodes.castleGodsWalls.material} />
      <mesh geometry={nodes.castleWalls.geometry} material={nodes.castleWalls.material} />
      <mesh geometry={nodes.castlePilars.geometry} material={nodes.castlePilars.material} />
      <mesh geometry={nodes.atm.geometry} material={nodes.atm.material} />
      <mesh geometry={nodes.Mirror001.geometry} material={nodes.Mirror001.material} position={[-1.643, 1.474, -0.821]} rotation={[Math.PI / 2, 0, 2.038]} />
      <mesh geometry={nodes.MirrorPage.geometry} material={nodes.MirrorPage.material} position={[-1.643, 1.474, -0.821]} rotation={[Math.PI / 2, 0, 2.038]} />
    </group>
  )
}

useGLTF.preload('/models/CastleA.glb')
